In [44]:
import pandas as pd 

# Displaying maximum # of rows + columns in dataframe
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

hotlineData = "/Users/haleluyagetachew/desktop/uncleaned_datasets/hotlineData.csv"

# data sets
def single_dataframe():
    df1 = pd.read_csv(hotlineData)
    
    
    return df1

first = single_dataframe()

In [45]:
# Notice 10 attributes of the hotlineData are categorical feautures (i.e values in these 10 columns are not strictly numerical)

first

   year   hotlineContacts   casesReported  sexTrafficking  laborTrafficking  sexAndLabor  typeUnspecified  domesticWork beggingRings    factories restaurantFoodService peddlingRings healthBeautyServices landscapingService  construction  agriculture  illicitActivities travelingSalesCrews  illicitMassageSpaBusiness  hotelMotelBased  pornography  escortServices  residenceBasedCommercialSex  streetBased  otherVenues  onlineAdVenueUnknown  male  female genderMinorities  adult  minor  foreignNational  USCitiizenLPR  highIndicators  moderateIndicators  survivorVictimCalls
0   2019               533            187             127                36           11               13             6            0            0                     6             0                    0                  0             0  less than 3                  3                   4                         20               13           12               0                            9            0            0                     4    23     159                3    116     46               43             21             116                 279                  130
1   2018               437            168             112                31           11               14            11            0            0                     3   less than 3                    0        less than 3             0            0                  0         less than 3                         10                9            8               8                            0            0            0                     7    22     110      less than 3     81     41               27             20             185                 177                   97
2   2017               490            121              93                19            5                4             6  less than 3  less than 3                     3             0                    0                  0             4            0                  0                   0                          9               11            0               0                            9            0            8                     8    15     103      less than 3     69     48               33             29             105                 101                   56
3   2016               594            167             126                29            7                5            14            3            0           less than 3             0                    0                  0             0  less than 3                  0         less than 3                         12               12            0               7                            9            0            0                    16    17     149                0     99     71               51             46             210                 126                   89
4   2015               497            122              96                18  less than 3                7            10            0            0           less than 3             0          less than 3                  0             0            0                  0                   3                          0                9            0               6                            7            5            0                     6     7     110      less than 3     83     34               29             49              94                  91                   88

In [42]:
import pandas as pd

# One Hot Encoding will be used to turn categorical variables into quantitative variables.

# creating indicator variables and changing columns for clarity
dummy_variable_1 = pd.get_dummies(first['sexAndLabor']).rename(columns=lambda x: 'sexAndLabor_' + str(x))
dummy_variable_2 = pd.get_dummies(first['beggingRings']).rename(columns=lambda x: 'beggingRings_' + str(x))
dummy_variable_3 = pd.get_dummies(first['factories']).rename(columns=lambda x: 'factories_' + str(x))
dummy_variable_4 = pd.get_dummies(first['restaurantFoodService']).rename(columns=lambda x: 'restaurantFoodService_' + str(x))
dummy_variable_5 = pd.get_dummies(first['peddlingRings']).rename(columns=lambda x: 'peddlingRings_' + str(x))
dummy_variable_6 = pd.get_dummies(first['healthBeautyServices']).rename(columns=lambda x: 'healthBeautyServices_' + str(x))
dummy_variable_7 = pd.get_dummies(first['landscapingService']).rename(columns=lambda x: 'landscapingService_' + str(x))
dummy_variable_8 = pd.get_dummies(first['agriculture']).rename(columns=lambda x: 'agriculture_' + str(x))
dummy_variable_9 = pd.get_dummies(first['travelingSalesCrews']).rename(columns=lambda x: 'travelingSalesCrews_' + str(x))
dummy_variable_10 = pd.get_dummies(first['genderMinorities']).rename(columns=lambda x: 'genderMinorities_' + str(x))


# merging new data frame with original data frame
first = pd.concat([first, dummy_variable_1, dummy_variable_2, dummy_variable_3, dummy_variable_4, dummy_variable_5, dummy_variable_6, dummy_variable_7, dummy_variable_8, dummy_variable_9, dummy_variable_10], axis=1)


# merge the new df to the original df and drop the original column names that were categorical
first.drop(['sexAndLabor', 'beggingRings','factories','restaurantFoodService','peddlingRings','healthBeautyServices','landscapingService','agriculture','travelingSalesCrews','genderMinorities'], axis=1, inplace=True)

In [43]:
first

,year,hotlineContacts,casesReported,sexTrafficking,laborTrafficking,typeUnspecified,domesticWork,factories,restaurantFoodService,peddlingRings,healthBeautyServices,landscapingService,construction,agriculture,illicitActivities,travelingSalesCrews,illicitMassageSpaBusiness,hotelMotelBased,pornography,escortServices,residenceBasedCommercialSex,streetBased,otherVenues,onlineAdVenueUnknown,male,female,genderMinorities,adult,minor,foreignNational,USCitiizenLPR,highIndicators,moderateIndicators,survivorVictimCalls,sexAndLabor_11,sexAndLabor_5,sexAndLabor_7,sexAndLabor_less than 3,beggingRings_0,beggingRings_3,beggingRings_less than 3,factories_0,factories_less than 3,restaurantFoodService_3,restaurantFoodService_6,restaurantFoodService_less than 3,peddlingRings_0,peddlingRings_less than 3,healthBeautyServices_0,healthBeautyServices_less than 3,landscapingService_0,landscapingService_less than 3,agriculture_0,agriculture_less than 3,travelingSalesCrews_0,travelingSalesCrews_3,travelingSalesCrews_4,travelingSalesCrews_less than 3,genderMinorities_0,genderMinorities_3,genderMinorities_less than 3
0,2019,533,187,127,36,13,6,0,6,0,0,0,0,less than 3,3,4,20,13,12,0,9,0,0,4,23,159,3,116,46,43,21,116,279,130,1,0,0,0,1,0,0,1,0,0,1,0,1,0,1,0,1,0,0,1,0,0,1,0,0,1,0
1,2018,437,168,112,31,14,11,0,3,less than 3,0,less than 3,0,0,0,less than 3,10,9,8,8,0,0,0,7,22,110,less than 3,81,41,27,20,185,177,97,1,0,0,0,1,0,0,1,0,1,0,0,0,1,1,0,0,1,1,0,0,0,0,1,0,0,1
2,2017,490,121,93,19,4,6,less than 3,3,0,0,0,4,0,0,0,9,11,0,0,9,0,8,8,15,103,less than 3,69,48,33,29,105,101,56,0,1,0,0,0,0,1,0,1,1,0,0,1,0,1,0,1,0,1,0,1,0,0,0,0,0,1
3,2016,594,167,126,29,5,14,0,less than 3,0,0,0,0,less than 3,0,less than 3,12,12,0,7,9,0,0,16,17,149,0,99,71,51,46,210,126,89,0,0,1,0,0,1,0,1,0,0,0,1,1,0,1,0,1,0,0,1,0,0,0,1,1,0,0
4,2015,497,122,96,18,7,10,0,less than 3,0,less than 3,0,0,0,0,3,0,9,0,6,7,5,0,6,7,110,less than 3,83,34,29,49,94,91,88,0,0,0,1,1,0,0,1,0,0,0,1,1,0,0,1,1,0,1,0,0,1,0,0,0,0,1

In [46]:
first.to_csv('quantifiedHotlineData')